### PR TITLE
ByIdentityProviderIdentifier

### PR DESCRIPTION
**Pull request by andrei-egeniq**
Tested with multiple accounts on demo.tiqr.org
Not tested with multiple accounts on multiple sites.

### CODE REVIEW

**Comment by andrei-egeniq** [comment]
fix for https://github.com/SURFnet/tiqr-client-android/issues/14

**Comment by ijansch** [comment]
Code looks good. @joostd do you happen to  know someone who could test this, just in case, in an app with multiple services? (e.g. if it still works if you mix identifies from demo.tiqr.org and another idp).

**Comment by joostd** [comment]
Yes, Eefje has tested this with both the demo and the stepup tiqr servers and both enrolment and authentication work fine.

**Comment by ijansch** [comment]
:+1:

**Pull request merged**
